FruitsTraceabilitySystem/Presentation/FruitsTraceabilitySystem.Web/Areas/Admin/Controllers/PackangingController.cs
using FruitsTraceabilitySystem.Application.Interfaces.Harvests;
using FruitsTraceabilitySystem.Application.Interfaces.Packages;
using FruitsTraceabilitySystem.Application.Interfaces.Packangings;
using FruitsTraceabilitySystem.Application.Interfaces.Products;
using FruitsTraceabilitySystem.Application.Interfaces.Sortings;
using FruitsTraceabilitySystem.Application.ViewModels.Packangings;
using FruitsTraceabilitySystem.Application.ViewModels.Sortings;
using FruitsTraceabilitySystem.Domain.Models.SeedRoles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace FruitsTraceabilitySystem.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SeedRole.RoleAdmin)]
    public class PackangingController : Controller
    {
        #region Properties
        private readonly IPackangingService _packangingService;
        private readonly ISortingService _sortingService;
        private readonly IHarvestService _harvestService;
        private readonly IPackageService _packageService;
        private readonly IProductService _productService;
        #endregion

        #region Constructors
        public PackangingController(IPackangingService packangingService, ISortingService sortingService, IHarvestService harvestService, IPackageService packageService, IProductService productService)
        {
            _packangingService = packangingService ?? throw new ArgumentNullException(nameof(packangingService));
            _sortingService = sortingService ?? throw new ArgumentNullException(nameof(sortingService));
            _harvestService = harvestService ?? throw new ArgumentNullException(nameof(harvestService));
            _packageService = packageService ?? throw new ArgumentNullException(nameof(packageService));
            _productService = productService ?? throw new ArgumentNullException(nameof(productService));
        }
        #endregion

        #region Methods
        public IActionResult Index()
        {
            List<PackangingViewModel> packangings = _packangingService.GetAll(includeProperties: "ProductSorting,Package,User").ToList();
            packangings.ForEach(x =>
            {
                var sortings = _sortingService.GetFirstOrDefault(x.ProductSortingId, includeProperties: "Harvest");
                foreach (var sorting in sortings.ToString())
                {
                    x.ProductSortingName = _harvestService.GetFirstOrDefault(sortings.HarvestId, includeProperties: "Product").Product.Name;
                }
            });
            return View(packangings);
        }
        public IActionResult Created()
        {
            IEnumerable<SelectListItem> PackageList = _packageService.GetAll()
               .Select(x => new SelectListItem
               {
                   Text = x.Name,
                   Value = x.Id.ToString()
               });
            ViewBag.PackageList = PackageList;
            List<SortingViewModel> data = _sortingService.GetAll(includeProperties: "Harvest").ToList();
            data.ForEach(x =>
            {
                x.ProductName = _harvestService.GetFirstOrDefault(x.HarvestId, includeProperties: "Product").Product.Name;
            });
            IEnumerable<SelectListItem> SortingList = data.Select(x => new SelectListItem
            {
                Text = x.ProductName,
                Value = x.Id.ToString()
            });
            ViewBag.SortingList = SortingList;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Created(PackangingViewModel packanging)
        {
            if (ModelState.IsValid)
            {
                packanging.UserId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
                _packangingService.Add(packanging);
                TempData["success"] = "Packanging created successfully";
                return RedirectToAction("Index");
            }
            return View(packanging);
        }

        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var packanging = _packangingService.GetFirstOrDefault(Id, includeProperties: "ProductSorting,Package,User");
            IEnumerable<SelectListItem> PackageList = _packageService.GetAll()
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });
            List<SortingViewModel> sortings = _sortingService.GetAll(includeProperties: "Harvest").ToList();
            sortings.ForEach(x =>
            {
                x.ProductName = _harvestService.GetFirstOrDefault(x.HarvestId, includeProperties: "Product").Product.Name;
            });
            IEnumerable<SelectListItem> SortingList = sortings.Select(x => new SelectListItem
            {
                Text = x.ProductName,
                Value = x.Id.ToString()
            });
            ViewBag.PackageList = PackageList;
            ViewBag.ProductList = SortingList;
            if (packanging == null)
            {
                return NotFound();
            }
            return View(packanging);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(PackangingViewModel packangingView)
        {
            if (ModelState.IsValid)
            {
                packangingView.UserId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
                _packangingService.Update(packangingView);
                TempData["success"] = "Packanging edit successfully";
                return RedirectToAction("Index");
            }
            return View(packangingView);
        }

        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var packangingView = _packangingService.GetFirstOrDefault(Id, includeProperties: "ProductSorting,Package,User");
            IEnumerable<SelectListItem> PackageList = _packageService.GetAll()
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });
            List<SortingViewModel> sortings = _sortingService.GetAll(includeProperties: "Harvest").ToList();
            sortings.ForEach(x =>
            {
                x.ProductName = _harvestService.GetFirstOrDefault(x.HarvestId, includeProperties: "Product").Product.Name;
            });
            IEnumerable<SelectListItem> SortingList = sortings.Select(x => new SelectListItem
            {
                Text = x.ProductName,
                Value = x.Id.ToString()
            });
            ViewBag.PackageList = PackageList;
            ViewBag.ProductList = SortingList;
            if (packangingView == null)
            {
                return NotFound();
            }
            return View(packangingView);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteProduct(int? Id)
        {
            _packangingService.Delete(Id);
            TempData["success"] = "Packanging delete successfully";
            return RedirectToAction("Index");
        }
        #endregion
    }
}

FruitsTraceabilitySystem/Presentation/FruitsTraceabilitySystem.Web/Areas/Admin/Views/Packanging/Created.cshtml
@using FruitsTraceabilitySystem.Application.ViewModels.Packangings
@model PackangingViewModel
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Created Packaging</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Package"></label>
            <select asp-for="PackageId" asp-items="ViewBag.PackageList" class="form-select">
                <option disabled selected>--Selected Package--</option>
            </select>
            <span asp-validation-for="Package" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="ProductSorting"></label>
            <select asp-for="ProductSortingId" asp-items="ViewBag.SortingList" class="form-select">
                <option disabled selected>--Selected Sorting--</option>
            </select>
            <span asp-validation-for="ProductSorting" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px"><i class="fad fa-plus"></i> Created</button>
        <a asp-controller="Packanging" asp-action="Index" class="btn btn-danger" style="width:150px"><i class="fad fa-long-arrow-left"></i> Back</a>
    </div>
</form>
@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
}

FruitsTraceabilitySystem/Presentation/FruitsTraceabilitySystem.Web/Areas/Admin/Views/Packanging/Delete.cshtml
@using FruitsTraceabilitySystem.Application.ViewModels.Packangings
@model PackangingViewModel

<form method="post" asp-action="Delete">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Packaging</h2>
            <hr />
        </div>
         <div class="mb-3">
            <label asp-for="Package"></label>
             <select asp-for="PackageId" asp-items="ViewBag.PackageList" disabled class="form-select">
                    <option disabled selected>--Selected Package--</option>
             </select>
            <span asp-validation-for="Package" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="ProductSorting"></label>
             <select asp-for="ProductSortingId" asp-items="ViewBag.ProductList" disabled class="form-select">
                    <option disabled selected>--Selected Product--</option>
             </select>
            <span asp-validation-for="ProductSortingName" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px"><i class="fad fa-edit"></i> Delete</button>
        <a asp-controller="Packanging" asp-action="Index" class="btn btn-danger" style="width:150px"><i class="fad fa-long-arrow-left"></i> Back</a>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

FruitsTraceabilitySystem/Presentation/FruitsTraceabilitySystem.Web/Areas/Admin/Views/Packanging/Edit.cshtml
@using FruitsTraceabilitySystem.Application.ViewModels.Packangings
@model PackangingViewModel

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Packaging</h2>
            <hr />
        </div>
         <div class="mb-3">
            <label asp-for="Package"></label>
             <select asp-for="PackageId" asp-items="ViewBag.PackageList" class="form-select">
                    <option disabled selected>--Selected Package--</option>
             </select>
            <span asp-validation-for="Package" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="ProductSorting"></label>
             <select asp-for="ProductSortingId" asp-items="ViewBag.ProductList" class="form-select">
                    <option disabled selected>--Selected Product--</option>
             </select>
            <span asp-validation-for="ProductSortingName" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px"><i class="fad fa-edit"></i> Update</button>
        <a asp-controller="Packanging" asp-action="Index" class="btn btn-danger" style="width:150px"><i class="fad fa-long-arrow-left"></i> Back</a>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

FruitsTraceabilitySystem/Presentation/FruitsTraceabilitySystem.Web/Areas/Admin/Views/Packanging/Index.cshtml
@using FruitsTraceabilitySystem.Application.ViewModels.Packangings
@model IEnumerable<PackangingViewModel>
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Packanging List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Packanging" asp-action="Created" class="btn btn-primary"><i class="far fa-plus-circle"></i> &nbsp; New Packanging</a>
        </div>
    </div>
</div>
<br />
<br />
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Package Name
            </th>
            <th>
                Product Sorting
            </th>
            <th>
                User Id
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var packanging in Model)
        {
            <tr>
                <td width="35%">
                    @packanging.Package.Name
                </td>
                <td width="30%">
                    @packanging.ProductSortingName
                </td>
                <td width="20%">
                    @packanging.User.Name
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Packanging" class="btn btn-primary mx-2" asp-route-id="@packanging.Id" asp-action="Edit"><i class="fad fa-file-edit"></i></a>
                        <a asp-controller="Packanging" class="btn btn-danger mx-2" asp-route-id="@packanging.Id" asp-action="Delete"><i class="fad fa-trash-alt"></i></a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>