FruitsTraceabilitySystem/Presentation/FruitsTraceabilitySystem.Web/Areas/Admin/Controllers/HarvestController.cs
using FruitsTraceabilitySystem.Application.Interfaces.Harvests;
using FruitsTraceabilitySystem.Application.Interfaces.Products;
using FruitsTraceabilitySystem.Application.ViewModels.Harvests;
using FruitsTraceabilitySystem.Domain.Models.SeedRoles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace FruitsTraceabilitySystem.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SeedRole.RoleAdmin)]
    public class HarvestController : Controller
    {
        #region Properties
        private readonly IHarvestService _harvestService;
        private readonly IProductService _productService;

        #endregion

        #region Constructors
        public HarvestController(IHarvestService harvestService, IProductService productService)
        {
            _harvestService = harvestService ?? throw new ArgumentNullException(nameof(harvestService));
            _productService = productService ?? throw new ArgumentNullException(nameof(productService));
        }
        #endregion

        #region Methods
        public IActionResult Index()
        {
            IEnumerable<HarvestViewModel> harvests = _harvestService.GetAll(includeProperties: "Product,User");
            return View(harvests);
        }
        public IActionResult Created()
        {
            IEnumerable<SelectListItem> ProductList = _productService.GetAll()
               .Select(x => new SelectListItem
               {
                   Text = x.Name,
                   Value = x.Id.ToString()
               });
            ViewBag.ProductList = ProductList;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Created(HarvestViewModel harvest)
        {
            if (ModelState.IsValid)
            {
                harvest.UserId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
                _harvestService.Add(harvest);
                TempData["success"] = "Harvest created successfully";
                return RedirectToAction("Index");
            }
            return View(harvest);
        }

        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var harvest = _harvestService.GetFirstOrDefault(Id, includeProperties: "Product,User");
            IEnumerable<SelectListItem> ProductList = _productService.GetAll()
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });
            ViewBag.ProductList = ProductList;
            if (harvest == null)
            {
                return NotFound();
            }
            return View(harvest);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(HarvestViewModel harvest)
        {
            if (ModelState.IsValid)
            {
                harvest.UserId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
                _harvestService.Update(harvest);
                TempData["success"] = "Harvest edit successfully";
                return RedirectToAction("Index");
            }
            return View(harvest);
        }

        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var harvest = _harvestService.GetFirstOrDefault(Id, includeProperties: "Product,User");
            IEnumerable<SelectListItem> ProductList = _productService.GetAll()
               .Select(x => new SelectListItem
               {
                   Text = x.Name,
                   Value = x.Id.ToString()
               });
            ViewBag.ProductList = ProductList;
            if (harvest == null)
            {
                return NotFound();
            }
            return View(harvest);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteProduct(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            _harvestService.Delete(Id);
            TempData["success"] = "Harvest delete successfully";
            return RedirectToAction("Index");
        }
        #endregion
    }
}

FruitsTraceabilitySystem/Presentation/FruitsTraceabilitySystem.Web/Areas/Admin/Controllers/PackageController.cs
using FruitsTraceabilitySystem.Application.Interfaces.Packages;
using FruitsTraceabilitySystem.Application.ViewModels.Packages;
using FruitsTraceabilitySystem.Domain.Models.SeedRoles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FruitsTraceabilitySystem.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SeedRole.RoleAdmin)]
    public class PackageController : Controller
    {
        #region Properties
        private readonly IPackageService _packageService;
        #endregion

        #region Constructors
        public PackageController(IPackageService packageService)
        {
            _packageService = packageService ?? throw new ArgumentNullException(nameof(packageService));
        }
        #endregion

        #region Methods
        public IActionResult Index()
        {
            IEnumerable<PackageViewModel> packages = _packageService.GetAll();
            return View(packages);
        }
        public IActionResult Created()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Created(PackageViewModel package)
        {
            if (ModelState.IsValid)
            {
                _packageService.Add(package);
                TempData["success"] = "Package created successfully";
                return RedirectToAction("Index");
            }
            return View(package);
        }

        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var package = _packageService.GetFirstOrDefault(Id);
            if (package == null)
            {
                return NotFound();
            }
            return View(package);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(PackageViewModel packageView)
        {
            if (ModelState.IsValid)
            {
                _packageService.Update(packageView);
                TempData["success"] = "Package edit successfully";
                return RedirectToAction("Index");
            }
            return View(packageView);
        }

        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var packageView = _packageService.GetFirstOrDefault(Id);
            if (packageView == null)
            {
                return NotFound();
            }
            return View(packageView);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteProduct(int? Id)
        {
            _packageService.Delete(Id);
            TempData["success"] = "Package delete successfully";
            return RedirectToAction("Index");
        }
        #endregion
    }
}

FruitsTraceabilitySystem/Presentation/FruitsTraceabilitySystem.Web/Areas/Admin/Controllers/ProductController.cs
using FruitsTraceabilitySystem.Application.Interfaces.Categories;
using FruitsTraceabilitySystem.Application.Interfaces.Products;
using FruitsTraceabilitySystem.Application.ViewModels.Products;
using FruitsTraceabilitySystem.Domain.Models.SeedRoles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FruitsTraceabilitySystem.Web.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SeedRole.RoleAdmin)]
    public class ProductController : Controller
    {
        #region Properties
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        #endregion

        #region Constructors
        public ProductController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService ?? throw new ArgumentNullException(nameof(productService));
            _categoryService = categoryService ?? throw new ArgumentNullException(nameof(categoryService));
        }
        #endregion

        #region Methods
        public IActionResult Index()
        {
            IEnumerable<ProductViewModel> products = _productService.GetAll(includeProperties: "Category");
            return View(products);
        }
        public IActionResult Created()
        {
            IEnumerable<SelectListItem> CategoryList = _categoryService.GetAll()
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });
            ViewBag.CategoryList = CategoryList;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Created(ProductViewModel product)
        {
            if (ModelState.IsValid)
            {
                _productService.Add(product);
                TempData["success"] = "Product created successfully";
                return RedirectToAction("Index");
            }
            return View(product);
        }

        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var product = _productService.GetFirstOrDefault(Id, includeProperties: "Category");
            IEnumerable<SelectListItem> CategoryList = _categoryService.GetAll()
               .Select(x => new SelectListItem
               {
                   Text = x.Name,
                   Value = x.Id.ToString()
               });
            ViewBag.CategoryList = CategoryList;
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ProductViewModel product)
        {
            if (ModelState.IsValid)
            {
                _productService.Update(product);
                TempData["success"] = "Product edit successfully";
                return RedirectToAction("Index");
            }
            return View(product);
        }

        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var product = _productService.GetFirstOrDefault(Id, includeProperties: "Category");
            IEnumerable<SelectListItem> CategoryList = _categoryService.GetAll()
               .Select(x => new SelectListItem
               {
                   Text = x.Name,
                   Value = x.Id.ToString()
               });
            ViewBag.CategoryList = CategoryList;
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteProduct(int? Id)
        {
            _productService.Delete(Id);
            TempData["success"] = "Product delete successfully";
            return RedirectToAction("Index");
        }
        #endregion
    }
}

FruitsTraceabilitySystem/Presentation/FruitsTraceabilitySystem.Web/Areas/Admin/Controllers/SortingController.cs
using FruitsTraceabilitySystem.Application.Interfaces.Harvests;
using FruitsTraceabilitySystem.Application.Interfaces.Sortings;
using FruitsTraceabilitySystem.Application.ViewModels.Sortings;
using FruitsTraceabilitySystem.Domain.Models.SeedRoles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace FruitsTraceabilitySystem.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SeedRole.RoleAdmin)]
    public class SortingController : Controller
    {
        #region Properties
        private readonly IHarvestService _harvestService;
        private readonly ISortingService _sortingService;
        #endregion

        #region Constructors
        public SortingController(IHarvestService harvestService, ISortingService sortingService)
        {
            _harvestService = harvestService ?? throw new ArgumentNullException(nameof(harvestService));
            _sortingService = sortingService ?? throw new ArgumentNullException(nameof(sortingService));
        }
        #endregion

        #region Methods
        public IActionResult Index()
        {
            List<SortingViewModel> harvests = _sortingService.GetAll(includeProperties: "Harvest,User").ToList();
            harvests.ForEach(x =>
            {
                x.ProductName = _harvestService.GetFirstOrDefault(x.HarvestId, includeProperties: "Product,User").Product.Name;
            });
            //IEnumerable<SortingViewModel> harvests = _sortingService.GetAll(includeProperties: "Harvest,User").ToList();
            //foreach (var harvest in harvests)
            //{
            //    harvest.ProductName = _harvestService.GetFirstOrDefault(harvest.HarvestId, includeProperties: "Product,User").Product.Name;
            //}
            return View(harvests);
        }
        public IActionResult Created()
        {
            IEnumerable<SelectListItem> ProductList = _harvestService.GetAll(includeProperties: "Product,User")
               .Select(x => new SelectListItem
               {
                   Text = x.Product.Name,
                   Value = x.Id.ToString()
               });
            ViewBag.ProductList = ProductList;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Created(SortingViewModel sorting)
        {
            if (ModelState.IsValid)
            {
                sorting.UserId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
                _sortingService.Add(sorting);
                TempData["success"] = "Sorting created successfully";
                return RedirectToAction("Index");
            }
            return View(sorting);
        }

        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var sorting = _sortingService.GetFirstOrDefault(Id, includeProperties: "Harvest,User");
            //var test = _harvestService.GetFirstOrDefault(sorting.HarvestId, includeProperties: "Product,User").Product.Name;
            IEnumerable<SelectListItem> ProductList = _harvestService.GetAll("Product,User")
                .Select(x => new SelectListItem
                {
                    Text = x.Product.Name,
                    Value = x.Product.Id.ToString()
                });
            ViewBag.ProductList = ProductList;
            if (sorting == null)
            {
                return NotFound();
            }
            return View(sorting);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SortingViewModel sorting)
        {
            if (ModelState.IsValid)
            {
                sorting.UserId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
                _sortingService.Update(sorting);
                TempData["success"] = "Sorting edit successfully";
                return RedirectToAction("Index");
            }
            return View(sorting);
        }

        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var sorting = _sortingService.GetFirstOrDefault(Id, includeProperties: "Harvest,User");
            IEnumerable<SelectListItem> ProductList = _harvestService.GetAll("Product,User")
               .Select(x => new SelectListItem
               {
                   Text = x.Product.Name,
                   Value = x.Id.ToString()
               });
            ViewBag.ProductList = ProductList;
            if (sorting == null)
            {
                return NotFound();
            }
            return View(sorting);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteProduct(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            _sortingService.Delete(Id);
            TempData["success"] = "Sorting delete successfully";
            return RedirectToAction("Index");
        }
        #endregion
    }
}

FruitsTraceabilitySystem/Presentation/FruitsTraceabilitySystem.Web/Views/Shared/_Layout.cshtml
@using FruitsTraceabilitySystem.Domain.Models.SeedRoles
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FruitsTraceabilitySystem.Web</title>
    <link rel="stylesheet" href="~/css/BootswatchThems.css" />
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FruitsTraceabilitySystem.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FruitsTraceabilitySystem</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      @*<ul class="navbar-nav justify-content-center me-auto">*@
      <ul class="navbar-nav justify-content-center  me-auto">
       <li class="nav-item">
           <a class="nav-link active" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
           </li>
           @if(User.IsInRole(SeedRole.RoleAdmin)){
             <li class="nav-item">
               <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
           </li>
           <li class="nav-item">
               <a class="nav-link" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
           </li>
           <li class="nav-item">
               <a class="nav-link" asp-area="Admin" asp-controller="Harvest" asp-action="Index">Harvest</a>
           </li>
           <li class="nav-item">
               <a class="nav-link" asp-area="Admin" asp-controller="Sorting" asp-action="Index">Sorting</a>
           </li> 
           <li class="nav-item">
               <a class="nav-link" asp-area="Admin" asp-controller="Package" asp-action="Index">Package</a>
           </li> 
           <li class="nav-item">
               <a class="nav-link" asp-area="Admin" asp-controller="Packanging" asp-action="Index">Packanging</a>
           </li> 
            <li class="nav-item">
               <a class="nav-link" asp-area="Admin" asp-controller="Location" asp-action="Index">Locations</a>
           </li> 
           }
      </ul>
      <partial name="_LoginPartial" />
    </div>
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

   @* <footer class="footer text-muted bg-primary">
        <div class="container">
            &copy; 2022 - FruitsTraceabilitySystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FruitsTraceabilitySystem/Presentation/FruitsTraceabilitySystem.Web/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">toastr.success('@TempData["success"]')</script>
}
@if(TempData["error"] != null){
     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">toastr.success('@TempData["error"]')</script>
}