FruitsTraceabilitySystem/Presentation/FruitsTraceabilitySystem.Web/Areas/Admin/Controllers/LocationController.cs
using FruitsTraceabilitySystem.Application.Interfaces.Locations;
using FruitsTraceabilitySystem.Application.ViewModels.Locations;
using FruitsTraceabilitySystem.Domain.Models.SeedRoles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FruitsTraceabilitySystem.Web.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = SeedRole.RoleAdmin)]
    public class LocationController : Controller
    {
        #region Properties
        private readonly ILocationService _locationService;
        #endregion

        #region Constructors
        public LocationController(ILocationService locationService)
        {
            _locationService = locationService ?? throw new ArgumentNullException(nameof(locationService));
        }
        #endregion

        #region Methods
        public IActionResult Index()
        {
            IEnumerable<LocationViewModel> locations = _locationService.GetAll();
            return View(locations);
        }
        public IActionResult Created()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Created(LocationViewModel location)
        {
            if (ModelState.IsValid)
            {
                _locationService.Add(location);
                TempData["success"] = "Location created successfully";
                return RedirectToAction("Index");
            }
            return View(location);
        }
        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var location = _locationService.GetFirstOrDefault(Id);
            if (location == null)
            {
                return NotFound();
            }
            return View(location);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(LocationViewModel location)
        {
            if (ModelState.IsValid)
            {
                _locationService.Update(location);
                TempData["success"] = "Location edit successfully";
                return RedirectToAction("Index");
            }
            return View(location);
        }
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var location = _locationService.GetFirstOrDefault(Id);
            if (location == null)
            {
                return NotFound();
            }
            return View(location);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteProduct(int? Id)
        {
            _locationService.Delete(Id);
            TempData["success"] = "Location delete successfully";
            return RedirectToAction("Index");
        }
        #endregion
    }
}

FruitsTraceabilitySystem/Presentation/FruitsTraceabilitySystem.Web/Areas/Admin/Views/Location/Created.cshtml
@using FruitsTraceabilitySystem.Application.ViewModels.Locations

@model LocationViewModel

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Created Location</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
         <div class="mb-3">
            <label asp-for="PlaceName"></label>
            <input asp-for="PlaceName" class="form-control" />
            <span asp-validation-for="PlaceName" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px"><i class="fad fa-plus"></i> Created</button>
        <a asp-controller="Location" asp-action="Index" class="btn btn-danger" style="width:150px"><i class="fad fa-long-arrow-left"></i> Back</a>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

FruitsTraceabilitySystem/Presentation/FruitsTraceabilitySystem.Web/Areas/Admin/Views/Location/Delete.cshtml
@using FruitsTraceabilitySystem.Application.ViewModels.Locations

@model LocationViewModel

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Location</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="PlaceName"></label>
            <input asp-for="PlaceName" disabled class="form-control" />
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px"><i class="fad fa-trash-alt"></i> Delete</button>
        <a asp-controller="Location" disabled asp-action="Index" class="btn btn-primary" style="width:150px"><i class="fad fa-long-arrow-left"></i> Back</a>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

FruitsTraceabilitySystem/Presentation/FruitsTraceabilitySystem.Web/Areas/Admin/Views/Location/Edit.cshtml
@using FruitsTraceabilitySystem.Application.ViewModels.Locations
@model LocationViewModel

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Location</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="PlaceName"></label>
            <input asp-for="PlaceName" class="form-control" />
            <span asp-validation-for="PlaceName" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px"><i class="fad fa-edit"></i> Update</button>
        <a asp-controller="Location" asp-action="Index" class="btn btn-danger" style="width:150px"><i class="fad fa-long-arrow-left"></i> Back</a>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

FruitsTraceabilitySystem/Presentation/FruitsTraceabilitySystem.Web/Areas/Admin/Views/Location/Index.cshtml
@using FruitsTraceabilitySystem.Application.ViewModels.Locations

@model IEnumerable<LocationViewModel>


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Location List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Location" asp-action="Created" class="btn btn-primary"><i class="far fa-plus-circle"></i> &nbsp; New Location</a>
        </div>
    </div>
</div>
<br/>
<br/>
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Location Id
            </th>
             <th>
                Location Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var location in Model)
        {
            <tr>
                <td width="35%">
                    @location.Id
                </td> 
                <td width="30%">
                    @location.PlaceName
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Location" class="btn btn-primary mx-2" asp-route-id="@location.Id" asp-action="Edit"><i class="fad fa-file-edit"></i></a>
                        <a asp-controller="Location" class="btn btn-danger mx-2" asp-route-id="@location.Id" asp-action="Delete"><i class="fad fa-trash-alt"></i></a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>